### ISSUE TITLE
USB Microphone issue [SOLVED]

### ISSUE THREAD

**Issue by dexterlu** [alexa/alexa-avs-raspberry-pi#229]
After Run the client app by mvn exec:exec
I got an error message box : 
line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.

Could any one help?
Thanks alot.

**Comment by dexterlu** [comment]
Hi, 
Following http://stackoverflow.com/questions/11915469/java-sound-format-not-supported
Ths USB Microphone should not be default device on OS.

Thanks.

**Comment by tyeth** [comment]
? This is not solved. You may have spotted the problem and possibly the solution, but not shared the pull request, what's the situation?

**Comment by ajotwani** [comment]
@tyeth have you looked at this thread - https://github.com/amzn/alexa-avs-raspberry-pi/issues/50?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
